Repository falcosecurity/kernel-testing, pull requests merged in 2023-07, with the labels that each got.

#63 new(git-repos): accept new host keys when fetching git repos
  ansible-playbooks/roles/git_repos/tasks/main.yml
Labels: dco-signoff: yes, size/XS, approved, lgtm

#65 fix(scap-open): do not skip modern bpf probe on supported platforms
  ansible-playbooks/roles/scap_open/tasks/main.yml
  ansible-playbooks/roles/scap_open/vars/main.yml
Labels: dco-signoff: yes, size/XS, approved, lgtm

#66 docs: fix README
  README.md
Labels: dco-signoff: yes, size/XS, approved, lgtm

#67 chore(roles/scap_open): renamed output jsons.
  ansible-playbooks/roles/scap_open/tasks/main.yml
Labels: dco-signoff: yes, approved, lgtm, size/S

#68 cleanup(matrix_gen): renamed go module to fit new falcosecurity/kernel-testing repo name
  matrix_gen/go.mod
Labels: dco-signoff: yes, size/XS, approved, lgtm

#69 cleanup(matrix_gen/pkg,ci): refactor matrix_gen code.
  .github/workflows/matrix-gen-ci.yml
  matrix_gen/main.go
  matrix_gen/pkg/matrix/error.go
  matrix_gen/pkg/matrix/output.go
Labels: dco-signoff: yes, approved, lgtm, size/XL
